version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    tty: true
    privileged: true
    entrypoint: >
      sh -c "ollama serve & sleep 5 && ollama run deepseek-r1:1.5b && tail -f /dev/null"

volumes:
  ollama_data:
